packages/sdk/source/networks/network.ts
resubmitted https://github.com/ArkEcosystemArchive/platform-sdk/pull/1936
=> fix(sdk): use `coinName` in `Network#displayName`

packages/sdk-lsk/source/transaction-three.service.test.ts, packages/sdk-lsk/source/transaction-three.service.ts, packages/sdk/source/collections/paginator.test.ts, packages/sdk/source/collections/paginator.ts
remove duplicate function (getData, items) from paginator
only using items at DW
=> refactor(sdk): remove duplicate function in paginator

packages/sdk-lsk/source/__snapshots__/multi-signature.service.test.ts.snap, packages/sdk-lsk/source/__snapshots__/transaction-three.service.test.ts.snap, packages/sdk-lsk/source/multi-signature.service.ts, packages/sdk-lsk/source/transaction-three.service.test.ts, packages/sdk-lsk/source/transaction-three.service.ts, packages/sdk-lsk/source/transaction-two.service.ts, packages/sdk-lsk/source/transaction.dto.ts, packages/sdk-lsk/source/wallet.dto.ts, packages/sdk/source/dto/signed-transaction.contract.ts, packages/sdk/source/dto/signed-transaction.ts, packages/sdk/source/services/data-transfer-object.contract.ts, packages/sdk/source/services/data-transfer-object.service.ts
=> refactor(lsk): further normalise data

packages/sdk-ark/source/multi-signature.signer.ts, packages/sdk-ark/source/transaction.service.ts, packages/sdk/source/services/signatory.contract.ts, packages/sdk/source/services/signatory.service.ts, packages/sdk/source/signatories/index.ts, packages/sdk/source/signatories/multi-signature.ts, packages/sdk/source/signatories/signatory.test.ts, packages/sdk/source/signatories/signatory.ts
Forgot a few scenarios where this is actually required to be used.
=> fix(sdk): reintroduce `MultiSignatureSignatory`

common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/sdk-ark/package.json, packages/sdk-ark/source/multi-signature.service.ts
Filter out faulty data that clients might create.Filter out faulty data that clients might create.
=> refactor(ark): remove duplicate musig signatures

packages/sdk-lsk/source/transaction-type.service.ts, packages/sdk-lsk/source/transaction.dto.ts
3.0 is now on mainnet so 2.0 is legacy
=> refactor(lsk): invert production/legacy conditions

packages/sdk-ark/source/client.service.ts
the differentiation between main and devnet is not needed any longer.
=> fix(ark): change special handling to `bind` networks only

packages/sdk-lsk/source/networks/shared.ts
https://app.clickup.com/t/1exr01t
=> fix(lsk): reduce `votesPerWallet` for LSK from 20 to 10

packages/sdk-ark/source/__snapshots__/fee.service.test.ts.snap, packages/sdk-ark/source/fee.service.test.ts, packages/sdk-ark/source/fee.service.ts
https://app.clickup.com/t/1gb8b7t
=> fix(ark): update `FeeService` to take fee type into account

packages/sdk-lsk/source/networks/shared.ts
https://app.clickup.com/t/1gb9zva
=> chore(lsk): enable bip39 encryption

packages/sdk-lsk/source/client.service.ts
https://github.com/PayvoHQ/wallet/issues/499
- enables transaction lookup by type
- adds the `unlockToken` type
=> fix(lsk): set search params based on transaction type

packages/sdk-ark/source/client.service.ts
https://github.com/PayvoHQ/wallet/issues/497
=> fix(ark): transaction type for legacy coins

packages/sdk-ark/source/multi-signature.service.ts
=> fix(ark): parse unix timestamp stored in musig server

packages/ada/source/signed-transaction.dto.test.js, packages/atom/source/signed-transaction.dto.test.js, packages/dot/source/signed-transaction.dto.test.js, packages/egld/source/signed-transaction.dto.test.js, packages/eos/source/signed-transaction.dto.test.js, packages/nano/source/client.service.test.js, packages/nano/source/link.service.test.js, packages/nano/source/message.service.test.js, packages/nano/source/signed-transaction.dto.test.js, packages/nano/source/transaction.service.test.js, packages/neo/source/signed-transaction.dto.test.js, packages/xlm/source/signed-transaction.dto.test.js, packages/xrp/source/signed-transaction.dto.test.js
=> chore(nano): replace `jest` with `uvu`

.github/workflows/ci.yml, common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/test/package.json, packages/test/source/assert.test.js, packages/test/source/assert.ts, packages/test/source/index.ts
Resolves https://github.com/PayvoHQ/sdk/issues/422
=> feat(test): implement object matching with `zod`

packages/avax/source/address.service.test.js, packages/avax/source/client.service.test.js, packages/avax/source/key-pair.service.test.js, packages/avax/source/link.service.test.js, packages/avax/source/message.service.test.js, packages/avax/source/private-key.service.test.js, packages/avax/source/public-key.service.test.js, packages/avax/source/signed-transaction.dto.test.js, packages/avax/source/transaction.service.test.js, packages/avax/source/transaction.service.ts, packages/test/source/index.ts
This ensures all tests have their own local state and consistent error handling.
=> test(avax): consistent use of `describe`

packages/btc/source/transaction.service.ledger.test.js, packages/btc/source/transaction.service.test.js, packages/test/source/nock.ts
=> test(btc): fix nock leakage

packages/markets/source/drivers/coincap/index.test.js, packages/markets/source/drivers/coincap/transformers/historical-price-transformer.test.js, packages/markets/source/drivers/coincap/transformers/market-transformer.test.js, packages/markets/source/drivers/coincap/utils.test.js, packages/markets/source/drivers/coingecko/index.test.js, packages/markets/source/drivers/coingecko/transformers/historical-price-transformer.test.js, packages/markets/source/drivers/coingecko/transformers/historical-volume-transformer.test.js, packages/markets/source/drivers/coingecko/transformers/market-transformer.test.js, packages/markets/source/drivers/cryptocompare/index.test.js, packages/markets/source/drivers/cryptocompare/transformers/historical-price-transformer.test.js, packages/markets/source/drivers/cryptocompare/transformers/historical-volume-transformer.test.js, packages/markets/source/drivers/cryptocompare/transformers/market-transformer.test.js, packages/markets/source/index.test.js
=> test(markets): consistent use of `describe`

.github/workflows/ci.yml, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/test/package.json
=> ci: upgrade action dependencies

packages/zil/source/address.service.test.js, packages/zil/source/client.service.test.js, packages/zil/source/key-pair.service.test.js, packages/zil/source/link.service.test.js, packages/zil/source/private-key.service.test.js, packages/zil/source/public-key.service.test.js, packages/zil/source/signed-transaction.dto.test.js, packages/zil/source/transaction.service.test.js
=> test(zil): consistent use of `context`

packages/xrp/source/address.service.test.js, packages/xrp/source/client.service.test.js, packages/xrp/source/key-pair.service.test.js, packages/xrp/source/link.service.test.js, packages/xrp/source/message.service.test.js, packages/xrp/source/signed-transaction.dto.test.js, packages/xrp/source/transaction.dto.test.js
=> test(xrp): consistent use of `context`

packages/xlm/source/address.service.test.js, packages/xlm/source/client.service.test.js, packages/xlm/source/keys.service.test.js, packages/xlm/source/link.service.test.js, packages/xlm/source/message.service.test.js, packages/xlm/source/private-key.service.test.js, packages/xlm/source/public-key.service.test.js, packages/xlm/source/signed-transaction.dto.test.js, packages/xlm/source/transaction.service.test.js, packages/xlm/source/wallet.dto.test.js
=> test(xlm): consistent use of `context`

packages/sol/source/address.service.test.js, packages/sol/source/key-pair.service.test.js, packages/sol/source/link.service.test.js, packages/sol/source/private-key.service.test.js, packages/sol/source/public-key.service.test.js, packages/sol/source/signed-transaction.dto.test.js
=> test(sol): consistent use of `context`

packages/lsk/source/address.service.test.js, packages/lsk/source/client.service.test.js, packages/lsk/source/fee.service.test.js, packages/lsk/source/key-pair.service.test.js, packages/lsk/source/link.service.test.js, packages/lsk/source/message.service.test.js, packages/lsk/source/multi-signature.service.test.js, packages/lsk/source/private-key.service.test.js, packages/lsk/source/public-key.service.test.js, packages/lsk/source/signed-transaction.dto.test.js, packages/lsk/source/transaction.dto.test.js, packages/lsk/source/transaction.service.test.js, packages/lsk/source/wallet.dto.test.js, packages/lsk/source/wif.service.test.js
=> test(lsk): consistent use of `context`

packages/luna/source/link.service.test.js
=> test(luna): consistent use of `context`

packages/news/source/blockfolio.test.js, packages/news/source/feed.test.js
=> test(news): consistent use of `context`

packages/nano/source/client.service.test.js, packages/nano/source/link.service.test.js, packages/nano/source/message.service.test.js, packages/nano/source/signed-transaction.dto.test.js, packages/nano/source/transaction.service.test.js
=> test(nano): consistent use of `context`

packages/sdk/source/coin-factory.test.js, packages/sdk/source/coin.test.js, packages/sdk/source/config.test.js, packages/sdk/source/http-request.test.js, packages/sdk/source/http-response.test.js, packages/sdk/source/manifest.test.js, packages/sdk/source/network-repository.test.js, packages/sdk/source/network.test.js, packages/sdk/source/paginator.test.js, packages/sdk/source/transactions.collection.test.js, packages/sdk/source/wallets.collection.test.js
=> test(sdk): consistent use of `context`

packages/intl/source/datetime.test.js, packages/intl/source/money.test.js
=> test(intl): consistent use of `context`

packages/eos/source/client.service.test.js, packages/eos/source/link.service.test.js, packages/eos/source/message.service.test.js, packages/eos/source/signed-transaction.dto.test.js, packages/eos/source/wallet.dto.test.js
=> test(eos): consistent use of `context`

packages/helpers/source/assign.test.js, packages/helpers/source/bignumber.test.js, packages/helpers/source/censor.test.js, packages/helpers/source/collection.test.js, packages/helpers/source/find.test.js, packages/helpers/source/has-some-property.test.js, packages/helpers/source/immutable/order-by.test.js, packages/helpers/source/immutable/sort-by-desc.test.js, packages/helpers/source/immutable/sort-by.test.js, packages/helpers/source/is-enumerable.test.js, packages/helpers/source/key-by.test.js, packages/helpers/source/lower-first.test.js, packages/helpers/source/map-values.test.js, packages/helpers/source/order-by.test.js, packages/helpers/source/partition.test.js, packages/helpers/source/reject.test.js, packages/helpers/source/sort-by-desc.test.js, packages/helpers/source/sort-by.test.js, packages/helpers/source/upper-first.test.js, packages/helpers/source/uri.test.js, packages/helpers/source/validator.test.js
=> test(helpers): consistent use of `context`

packages/egld/source/address.service.test.js, packages/egld/source/client.service.test.js, packages/egld/source/key-pair.service.test.js, packages/egld/source/link.service.test.js, packages/egld/source/message.service.test.js, packages/egld/source/private-key.service.test.js, packages/egld/source/public-key.service.test.js, packages/egld/source/signed-transaction.dto.test.js
=> test(egld): consistent use of `context`

packages/trx/source/address.service.test.js, packages/trx/source/client.service.test.js, packages/trx/source/key-pair.service.test.js, packages/trx/source/link.service.test.js, packages/trx/source/message.service.test.js, packages/trx/source/private-key.service.test.js, packages/trx/source/public-key.service.test.js, packages/trx/source/signed-transaction.dto.test.js, packages/trx/source/transaction.dto.test.js, packages/trx/source/transaction.service.test.js, packages/trx/source/wallet.dto.test.js, packages/trx/source/wif.service.test.js
=> test(trx): consistent use of `context`

packages/dot/source/address.service.test.js, packages/dot/source/key-pair.service.test.js, packages/dot/source/link.service.test.js, packages/dot/source/message.service.test.js, packages/dot/source/private-key.service.test.js, packages/dot/source/public-key.service.test.js, packages/dot/source/signed-transaction.dto.test.js, packages/dot/source/transaction.service.test.js
=> test(dot): consistent use of `context`

packages/atom/source/address.service.test.js, packages/atom/source/client.service.test.js, packages/atom/source/key-pair.service.test.js, packages/atom/source/link.service.test.js, packages/atom/source/message.service.test.js, packages/atom/source/private-key.service.test.js, packages/atom/source/public-key.service.test.js, packages/atom/source/signed-transaction.dto.test.js, packages/atom/source/transaction.dto.test.js, packages/atom/source/transaction.service.test.js, packages/atom/source/wallet.dto.test.js
=> test(atom): consistent use of `context`

packages/cryptography/source/aes.test.js, packages/cryptography/source/base64.test.js, packages/cryptography/source/bip32.test.js, packages/cryptography/source/bip38.test.js, packages/cryptography/source/bip39.test.js, packages/cryptography/source/pbkdf2.test.js, packages/cryptography/source/uuid.test.js
=> test(cryptography): consistent use of `context`

packages/ark/source/address.service.test.js, packages/ark/source/client.service.test.js, packages/ark/source/confirmed-transaction.dto.test.js, packages/ark/source/fee.service.test.js, packages/ark/source/key-pair.service.test.js, packages/ark/source/known-wallet.service.test.js, packages/ark/source/message.service.test.js, packages/ark/source/multi-signature.service.test.js, packages/ark/source/private-key.service.test.js, packages/ark/source/public-key.service.test.js, packages/ark/source/signed-transaction.dto.test.js, packages/ark/source/transaction.service.test.js, packages/ark/source/wallet.dto.test.js, packages/ark/source/wif.service.test.js
=> test(ark): consistent use of `context`

packages/ada/source/address-list.service.test.js, packages/ada/source/address.service.test.js, packages/ada/source/client.service.test.js, packages/ada/source/extended-public-key.service.test.js, packages/ada/source/key-pair.service.test.js, packages/ada/source/link.service.test.js, packages/ada/source/message.service.test.js, packages/ada/source/private-key.service.test.js, packages/ada/source/public-key.service.test.js, packages/ada/source/signed-transaction.dto.test.js, packages/ada/source/transaction.dto.test.js, packages/ada/source/transaction.service.test.js, packages/ada/source/wallet.dto.test.js
=> test(ada): consistent use of `context`

packages/http-fetch/source/request.ts
=> fixx(http-fetch): set mode to CORS

packages/helpers/source/bignumber.ts
=> refactor(helpers): export `BigNumber` class instead of default

packages/ark/package.json, packages/ark/source/address.service.ts, packages/ark/source/crypto/identities/address.test.ts, packages/ark/source/crypto/identities/address.ts, packages/ark/source/crypto/identities/contracts.ts, packages/ark/source/crypto/identities/errors.ts, packages/ark/source/crypto/identities/keys.test.ts, packages/ark/source/crypto/identities/keys.ts, packages/ark/source/crypto/identities/private-key.test.ts, packages/ark/source/crypto/identities/private-key.ts, packages/ark/source/crypto/identities/public-key.test.ts, packages/ark/source/crypto/identities/public-key.ts, packages/ark/source/crypto/identities/wif.test.ts, packages/ark/source/crypto/identities/wif.ts, packages/ark/source/key-pair.service.ts, packages/ark/source/ledger.service.test.ts, packages/ark/source/private-key.service.ts, packages/ark/source/public-key.service.ts, packages/ark/source/wif.service.ts, packages/ark/test/crypto/identity.json, packages/ark/test/crypto/networks.json, packages/cryptography/source/index.ts, packages/test/source/assert.ts, pnpm-lock.yaml
Integrates https://github.com/ArkEcosystem/typescript-crypto-identities into the ARK package for greater control over dependencies and bundle size.
=> refactor(ark): integrate crypto identity derivation

packages/cryptography/source/base58-check.ts
=> refactor(cryptography): use `@noble/hashes` for base58 hashing

packages/helpers/package.json, packages/helpers/source/uri.test.ts, packages/helpers/source/uri.ts, pnpm-lock.yaml
=> refactor(helpers): use query string package that supports browsers

packages/cryptography/source/uuid.test.ts, packages/cryptography/source/uuid.ts
=> refactor(cryptography): remove unused `UUID` methods

package.json, packages/profiles/package.json, packages/profiles/source/local.storage.test.ts, packages/profiles/source/local.storage.ts, pnpm-lock.yaml
Closes https://github.com/PayvoHQ/sdk/issues/635
More of a workaround than a real fix, the issue is being tracked via https://github.com/localForage/localForage/issues/722#issuecomment-767765957. A better solution could be provided that does not involve changes in the LocalStorage class.
=> test(profiles): fix `LocalStorage` test by using a memory driver

packages/eth/package.json, packages/eth/source/units.test.ts, packages/eth/source/units.ts, pnpm-lock.yaml
Resolves https://github.com/PayvoHQ/sdk/issues/647
=> refactor(eth): remove `bn.js` dependency in favour of native `BigInt`

packages/helpers/source/index.ts, packages/helpers/source/uint8.test.ts, packages/helpers/source/uint8.ts
Part of https://github.com/PayvoHQ/sdk/issues/646
=> feat(helpers): implement conversion helpers for `Uint8Array`

packages/cryptography/source/hash.ts
Uses the `TextEncoder` class for string handling and builds a `Uint8Array` from the ground up for `Buffer`
=> refactor(cryptography): normalise value into `Uint8Array` before hashing

packages/cryptography/source/hash.ts, packages/cryptography/source/internal/buffer-to-uint8array.ts, packages/cryptography/source/secp256k1.ts
=> refactor(cryptography): turn signatures, hashes and keys into `Uint8Array`

packages/cryptography/source/base58-check.ts, packages/cryptography/source/base58.ts, packages/cryptography/source/buffoon.ts, packages/cryptography/source/hash.ts, packages/cryptography/source/hdkey.ts, packages/cryptography/source/internal/buffer-to-uint8array.ts
=> refactor(cryptography): normalise all buffers into `Uint8Array`

packages/ada/package.json, packages/ark/package.json, packages/ark/source/crypto/identities/keys.ts, packages/atom/package.json, packages/avax/package.json, packages/btc/package.json, packages/cryptography/package.json, packages/dot/package.json, packages/egld/package.json, packages/eos/package.json, packages/eth/package.json, packages/fetch/package.json, packages/helpers/package.json, packages/intl/package.json, packages/ledger/package.json, packages/lsk/package.json, packages/luna/package.json, packages/markets/package.json, packages/nano/package.json, packages/neo/package.json, packages/news/package.json, packages/profiles/package.json, packages/sdk/package.json, packages/sol/package.json, packages/test/package.json, packages/trx/package.json, packages/xlm/package.json, packages/xrp/package.json, packages/zil/package.json, pnpm-lock.yaml
=> chore: update development dependencies

packages/ark/source/ledger.service.ts
Related to https://github.com/PayvoHQ/wallet/issues/923
Adds a new option to track the wallet loading progress, used here https://github.com/PayvoHQ/wallet/pull/951
=> refactor(ark): add progress handler to track the loaded wallets

packages/sdk/source/ledger.contract.ts
Following this PR https://github.com/PayvoHQ/sdk/pull/704 I missed updating the contract so the new parameter is accepted
=> fix(sdk): update scan method contract

packages/helpers/source/uri.test.ts, packages/helpers/source/uri.ts
related to this task https://github.com/PayvoHQ/wallet/issues/800
=> fix: adjust the URI generator

packages/ark/source/confirmed-transaction.dto.test.ts, packages/ark/source/wallet.dto.test.ts, packages/atom/source/client.service.test.ts, packages/btc/source/client.service.test.ts, packages/eos/source/wallet.dto.test.ts, packages/lsk/source/transaction.dto.test.ts, packages/neo/source/wallet.dto.test.ts, packages/test/package.json, packages/test/source/assert.test.ts, packages/test/source/assert.ts, packages/trx/source/wallet.dto.test.ts, packages/xlm/source/client.service.test.ts, packages/xlm/source/wallet.dto.test.ts, packages/xrp/source/client.service.test.ts, packages/xrp/source/confirmed-transaction.dto.test.ts, packages/xrp/source/wallet.dto.test.ts, packages/zil/source/client.service.test.ts, pnpm-lock.yaml
https://github.com/PayvoHQ/sdk/issues/696
=> refactor: automatically cast `BigNumber` instances in assertions

packages/ark/source/networks/xqr.mainnet.ts, packages/ark/source/networks/xqr.testnet.ts
This time paths instead of URLs changed.
=> fix(ark): adjust XQR explorer urls

packages/sdk/source/confirmed-transaction.dto.ts, packages/sdk/source/signed-transaction.dto.ts
Fixes https://github.com/ArkEcosystem/payvo-wallet/issues/1358.
=> refactor(sdk): check if transaction type is vote combination before other types

packages/profiles/source/environment.test.ts, packages/profiles/source/migrator.test.ts, packages/profiles/source/profile.enum.contract.ts, packages/profiles/source/profile.importer.test.ts, packages/profiles/source/profile.initialiser.ts, packages/profiles/source/profile.test.ts, packages/profiles/source/profile.validator.test.ts, packages/profiles/source/profile.validator.ts
Related to https://github.com/ArkEcosystem/payvo-wallet/issues/1057
Adds the `FallbackToDefaultNodes ` setting that is going to be used on the new server management section on the wallet
=> feat: add FallbackToDefaultNodes user profile setting

packages/ark/source/transaction.service.ts
=> fix(ark): force transaction version 2

packages/profiles/source/profile.validator.ts
Related to https://github.com/ArkEcosystem/payvo-wallet/issues/1057
Makes the new `FallbackToDefaultNodes` optional to prevent issues with migrations
=> refactor: make new FallbackToDefaultNodes setting optional

packages/ark/source/networks/bind.mainnet.ts, packages/ark/source/networks/bind.testnet.ts
=> refactor(bind): disable multisignature feature

packages/profiles/source/coin.service.ts, packages/profiles/source/host.repository.contract.ts, packages/profiles/source/host.repository.test.ts, packages/profiles/source/host.repository.ts
=> feat(profiles): add support for host names

packages/profiles/source/appearance.service.test.ts, packages/profiles/source/appearance.service.ts, packages/profiles/source/environment.test.ts, packages/profiles/source/migrator.test.ts, packages/profiles/source/profile.importer.test.ts, packages/profiles/source/profile.initialiser.test.ts, packages/profiles/source/profile.validator.test.ts
=> chore(profiles): replace default accent color

packages/profiles/source/host.repository.test.ts, packages/sdk/source/network.models.ts
Adds the enabled flag to the host repository
=> feat(profiles): add enabled flag to the host object

packages/profiles/source/coin.service.ts, packages/profiles/source/driver.ts, packages/profiles/source/environment.models.ts, packages/profiles/test/mocking.ts
=> refactor(profiles): use factory for network host selector function

packages/ark/source/request.ts, packages/profiles/source/driver.ts
=> fix(ark): pass host via callback

packages/profiles/source/coin.service.ts, packages/profiles/source/driver.ts, packages/profiles/test/mocking.ts
=> feat(profiles): add sensible default host selector

packages/profiles/source/coin.service.ts, packages/profiles/source/driver.ts, packages/profiles/test/mocking.ts
=> refactor(profiles): get hosts from repository instead of manifest

packages/ark/source/index.ts, packages/ark/source/prober.service.ts, packages/sdk/source/coin.ts, packages/sdk/source/prober.contract.ts, packages/sdk/source/prober.service.ts, packages/sdk/source/service-provider.contract.ts, packages/sdk/source/service-provider.ts, packages/sdk/source/services.ts
Adds a new `ProberService` that can be used to probe a host and see if it satisfies the conditions of the network.
=> feat: implement `ProberService`

packages/profiles/source/coin.service.contract.ts, packages/profiles/source/coin.service.ts, packages/profiles/source/profile.ts
=> feat(profiles): implement `CoinService#makeInstance`
