packages/sdk-ark/source/transaction.service.ts, packages/sdk-lsk/source/transaction-three.service.test.ts, packages/sdk-lsk/source/transaction-three.service.ts, packages/sdk/source/services/transaction.contract.ts
Reverting some changes because lisk is the exception to how multi-signatures generally work. Instead of changing the interface it'll be expected that the first N keys **(min)** are mandatory and that the remaining keys are optional. This leaves the interface intact and lets the coin itself figure out what to do with the keys.
=> refactor(sdk): update `WalletMultiSignature` interface

packages/sdk-ada/source/client.service.test.ts, packages/sdk-ada/source/client.service.ts, packages/sdk-ada/source/transaction.service.test.ts, packages/sdk-ark/source/transaction.service.test.ts, packages/sdk-ark/source/transaction.service.ts, packages/sdk-ark/test/fixtures/client/DKkBL5Mg9v1TPcKQrcUuW1VQrVFu8bh82Q.json, packages/sdk-atom/source/transaction.service.ts, packages/sdk-lsk/source/transaction-three.service.ts, packages/sdk-nano/source/transaction.service.test.ts, packages/sdk-trx/source/transaction.service.test.ts, packages/sdk-xlm/source/client.service.test.ts, packages/sdk-xlm/source/transaction.service.test.ts, packages/sdk-zil/source/transaction.service.test.ts, packages/sdk/source/services/multi-signature.contract.ts, packages/sdk/source/services/shared.contract.ts, packages/sdk/source/services/signatory.service.ts, packages/sdk/source/services/transaction.service.ts, packages/sdk/source/signatories/multi-signature.ts, packages/sdk/source/signatories/signatory.test.ts, packages/sdk/source/signatories/signatory.ts
Some adjustments to sign multi-signature transactions before broadcasting them.
=> refactor(sdk): add `multiSignature` property for signatories

packages/sdk-ark/source/networks/bind.mainnet.ts, packages/sdk/source/networks/network-repository.test.ts
https://app.clickup.com/t/1c20drh
I've seen [the latest PR](https://github.com/PayvoHQ/sdk/pull/139), but there's no mention in the task that it is only for dev/test network
If so, ignore this PR
=> chore(ark): remove IPFS transaction for Compendia networks

packages/sdk-ark/source/client.service.test.ts, packages/sdk-ark/source/client.service.ts
Related to: https://app.clickup.com/t/1c208d3
Currently, when calling the compendia API  for a wallet, the `vote` attribute is a main attribute (and not an attribute inside the `attributes` property)
This is not properly handled on the method to get the `votes`.
Because of that, the compendia wallets that have a vote are handled as if they didn't have votes on the desktop wallet as described on the issue.
=> fix(ark): handle vote when is not inside the `attributes` property

packages/sdk-lsk/source/signed-transaction.dto.test.ts, packages/sdk-lsk/source/signed-transaction.dto.ts
The goal of this PR is to update the `amount` method of `SignedTransactionData`. When the transaction type is "unlockToken", it will return the sum of the amount of all the unlock objects included.
=> refactor(lsk): calculate amount of `unlockToken` transaction

packages/sdk-lsk/source/transaction.dto.test.ts, packages/sdk-lsk/source/transaction.dto.ts
Same as https://github.com/PayvoHQ/sdk/pull/216 but for confirmed transactions.
=> refactor(lsk): calculate amount of `unlockToken` confirmed transaction

packages/sdk-ark/source/key-pair.service.ts, packages/sdk-lsk/source/address.service.test.ts, packages/sdk-lsk/source/address.service.ts, packages/sdk-lsk/source/key-pair.service.test.ts, packages/sdk-lsk/source/key-pair.service.ts, packages/sdk-lsk/source/private-key.service.test.ts, packages/sdk-lsk/source/private-key.service.ts, packages/sdk-lsk/source/public-key.service.test.ts, packages/sdk-lsk/source/public-key.service.ts, packages/sdk-lsk/source/wif.service.test.ts, packages/sdk-lsk/source/wif.service.ts, packages/sdk-lsk/test/fixtures/identity.ts
Depends on https://github.com/PayvoHQ/sdk/pull/237
=> fix(lsk): use locale on BIP39 validation

packages/sdk-ark/source/client.service.test.ts, packages/sdk-ark/source/client.service.ts, packages/sdk-lsk/source/client.service.ts
after [removing identifiers](https://github.com/PayvoHQ/profiles/pull/93) from query, we don't have the identifiers for [sent](https://github.com/PayvoHQ/profiles/blob/master/source/transaction-index.ts#L34) or [received](https://github.com/PayvoHQ/profiles/blob/master/source/transaction-index.ts#L41) method, so there is no need to check `recipientId`/`senderId` before set the address
also, there is no more multiple addresses in identifiers, [just single address](https://github.com/PayvoHQ/profiles/blob/master/source/transaction-index.ts#L24-L28)
=> refactor: remove redundant statements in `ClientService` after deleting identifiers from query

packages/sdk-ark/source/transaction.service.ts, packages/sdk/source/services/signatory.contract.ts, packages/sdk/source/services/signatory.service.ts, packages/sdk/source/signatories/confirmation-secret.ts, packages/sdk/source/signatories/index.ts, packages/sdk/source/signatories/signatory.test.ts, packages/sdk/source/signatories/signatory.ts
Adds the `ConfirmationSecretSignatory` class to support signing transactions with two secrets.
=> feat(sdk): add `ConfirmationSecretSignatory`

packages/profiles/source/wallet.mutator.test.ts, packages/profiles/source/wallet.mutator.ts
Related to https://github.com/PayvoHQ/wallet/pull/559.
Checking against public keys does not work, in case the second signature is sent from a cold wallet.
=> fix(profiles): check against wallet address in password validation

.github/workflows/cf.yml, common/config/rush/command-line.json, package.json, packages/ada/package.json, packages/ark/package.json, packages/atom/package.json, packages/avax/package.json, packages/btc/package.json, packages/cryptography/package.json, packages/dot/package.json, packages/egld/package.json, packages/eos/package.json, packages/eth/package.json, packages/helpers/package.json, packages/http-fetch/package.json, packages/intl/package.json, packages/lsk/package.json, packages/luna/package.json, packages/markets/package.json, packages/nano/package.json, packages/neo/package.json, packages/news/package.json, packages/profiles/package.json, packages/sdk/package.json, packages/sol/package.json, packages/trx/package.json, packages/xlm/package.json, packages/xrp/package.json, packages/zil/package.json, pnpm-lock.yaml
Instead of running prettier for each directly we just run it for `packages/**` from the root. This is faster than `rush prettier` and achieves the same. Also raises the minimum node version to ensure some dependencies work as intended.
=> chore: move `prettier` to root of repository

packages/test/source/describe.test.js, packages/test/source/describe.ts
> Resolves https://github.com/PayvoHQ/sdk/issues/419
This implements the exact syntax describe in the linked issue. This mostly mirrors jest but the big difference is that you need to destruct the callback to get access to all the hooks like before, after, only, skip, test and so on.
This is done this way to ensure that you are always creating everything in the local scope. Local scope in this context means everything inside the `describe` block. This ensures that no state is leaked between multiple suites in a single file.
It also exposes `assert` through the callback, which can also be imported from `@payvo/sdk-test` directly. This is done for consistency to make it clear where everything that is used is coming from. It also exports an `it` function which is an alias of `test`. The …
=> feat(test): implement `describe` for suites

packages/test/source/describe.test.js, packages/test/source/describe.ts
Implements a new `describeWithContext` method that can be used to create a pre-defined context for all tests within a suite. The context can be either an object, function or async function. If an async function is used the `describe` has to be awaited for the context function to resolve.
**Note:** Using this context is similar to using `beforeAll` and setting context. This is more of a handy shorthand, especially if you have some default objects for some constant values.
=> feat(test): implement context for describe

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, packages/test/package.json, packages/test/source/describe.test.js, packages/test/source/describe.ts, packages/test/source/each.ts
> Resolves https://github.com/PayvoHQ/sdk/issues/436
Implements an API to use datasets that has a nicer syntax than what jest has. You simply pass an array of datasets as the last argument that's it. They can then be accessed through the `dataset` property in the test callback.
=> feat(test): implement datasets

packages/lsk/source/client.service.test.js
Use the new context to stub and restore the `DateTime.make` method. Doesn't require stubbing inside of tests anymore.
=> test(lsk): fix `DateTime` mocks for client service

packages/ark/source/client.service.test.js, packages/ark/source/fee.service.test.js, packages/ark/source/known-wallet.service.test.js, packages/ark/source/ledger.service.test.js, packages/ark/source/multi-signature.service.test.js, packages/ark/source/transaction.service.test.js, packages/lsk/source/ledger.service.test.js, packages/news/source/blockfolio.test.js, packages/profiles/test/integration/ark.musig.registration.test.js, packages/profiles/test/integration/lsk.musig.registration.test.js, packages/test/source/describe.ts, packages/test/source/hooks.ts, packages/xlm/source/client.service.test.js, packages/xlm/source/transaction.service.test.js, packages/zil/source/client.service.test.js
Ensure that we always clean the nock state before running a new test. Saves the hassle of thinking about calling this manually. Will probably cause a bunch of tests to fail because of a brittle setup, fixing them one by one.
=> refactor(test): always clean nock mocks in `after` hooks

packages/avax/source/client.service.test.js, packages/test/source/describe.ts, packages/test/source/nock.ts
Use the [uvu hooks](https://github.com/lukeed/uvu/blob/master/src/index.js#L9) to manage the state of nock instead of doing it inside of `nock.fake`.
=> refactor(test): use `uvu` hooks to manage nock lifecycle

packages/neo/source/address.service.test.js, packages/neo/source/client.service.test.js, packages/neo/source/key-pair.service.test.js, packages/neo/source/link.service.test.js, packages/neo/source/message.service.test.js, packages/neo/source/private-key.service.test.js, packages/neo/source/public-key.service.test.js, packages/neo/source/signed-transaction.dto.test.js, packages/neo/source/transaction.dto.test.js, packages/neo/source/wallet.dto.test.js, packages/neo/source/wif.service.test.js
=> test(neo): consistent use of `context`

packages/http-fetch/source/request.test.js
=> test(http-fetch): consistent use of `context`

packages/avax/source/address.service.test.js, packages/avax/source/client.service.test.js, packages/avax/source/key-pair.service.test.js, packages/avax/source/link.service.test.js, packages/avax/source/message.service.test.js, packages/avax/source/private-key.service.test.js, packages/avax/source/public-key.service.test.js, packages/avax/source/signed-transaction.dto.test.js, packages/avax/source/transaction.service.test.js
=> test(avax): consistent use of `context`

packages/test/source/describe.ts
When writing tests there'll now be autocompletion for the destructured properties.
=> refactor(test): add types for `describe` methods

packages/ark/source/crypto/hash.ts, packages/cryptography/source/bech32.ts, packages/cryptography/source/index.ts, packages/cryptography/source/secp256k1.ts
=> refactor(cryptography): create abstractions for `bech32` and `secp256k1`

packages/cryptography/package.json, packages/cryptography/source/hash.test.ts, packages/cryptography/source/hash.ts, packages/profiles/source/cache.service.ts, pnpm-lock.yaml
Replaces `bcrypto` with `@noble/hashes` for hashing operations.
=> refactor(cryptography): use `@noble/hashes` for hashing

packages/ark/package.json, packages/cryptography/package.json, packages/cryptography/source/secp256k1.ts, pnpm-lock.yaml
https://github.com/cryptocoinjs/secp256k1-node/blob/master/API.md
> Functions work with Uint8Array. While Buffer is awesome, current version for browsers (feross/buffer) is out of date (compare to Node.js Buffer) and in future difference probably will be only bigger. But because Buffer extends Uint8Array, you can pass and receive Buffers easily. Also, work with native Uint8Array reduce final build size, if you do not use Buffer in your browser application.
=> refactor(cryptography): use `secp256k1` for non-schnorr functions

packages/ark/package.json, packages/ark/source/crypto/hash.ts, packages/atom/package.json, packages/cryptography/package.json, packages/cryptography/source/secp256k1.ts, pnpm-lock.yaml
Bundle `bcrypto` only for `ark` because no one else needs it. ARK needs it for the broken legacy schnorr implementation that it exposes.
=> refactor: bundle `bcrypto` only with `ark`

packages/ark/package.json, packages/ark/source/crypto/bcrypto/asn1.ts, packages/ark/source/crypto/bcrypto/assert.ts, packages/ark/source/crypto/bcrypto/batch-rng.ts, packages/ark/source/crypto/bcrypto/bn.ts, packages/ark/source/crypto/bcrypto/chacha20.ts, packages/ark/source/crypto/bcrypto/custom.ts, packages/ark/source/crypto/bcrypto/ecdsa.ts, packages/ark/source/crypto/bcrypto/elliptic.ts, packages/ark/source/crypto/bcrypto/hmac-drbg.ts, packages/ark/source/crypto/bcrypto/hmac.ts, packages/ark/source/crypto/bcrypto/random.ts, packages/ark/source/crypto/bcrypto/schnorr-legacy.ts, packages/ark/source/crypto/bcrypto/secp256k1.ts, packages/ark/source/crypto/bcrypto/sha256.ts, packages/ark/source/crypto/hash.ts
Title and also removes `NODE_BACKEND=js` because we now only include the pure JavaScript implementations.
=> refactor(ark): adjust some `bcrypto` exports to match project style

packages/trx/package.json, packages/trx/source/address.service.test.ts, packages/trx/source/address.service.ts, pnpm-lock.yaml
> Resolves https://github.com/PayvoHQ/sdk/issues/478
Replaces `multicoin-address-validator` with a much smaller implementation that reuses our existing hashing and base58 implementations.
=> feat(trx): improve address validation implementation

packages/trx/source/address.service.ts
Bit of cleanup for Tron address validation for consistency with other packages.
=> refactor(trx): use `Buffer.compare` for address checksum comparison

packages/ark/source/crypto/transactions/types/ipfs.ts, packages/atom/source/address.service.ts, packages/cryptography/package.json, packages/cryptography/source/base58-check.test.ts, packages/cryptography/source/base58-check.ts, packages/cryptography/source/base58.test.ts, packages/cryptography/source/base58.ts, packages/cryptography/source/bech32.ts, packages/trx/source/address.service.ts, pnpm-lock.yaml
Replaces `bech32` and `base-x` with https://github.com/paulmillr/micro-base which has 0 dependencies and is actively maintained.
=> refactor(cryptography): use `micro-base` for `base58` and `bech32` operations

packages/cryptography/source/hash.ts, packages/eth/package.json, packages/eth/source/address.service.ts, packages/eth/source/client.service.test.ts, packages/eth/source/client.service.ts, packages/eth/source/confirmed-transaction.dto.ts, packages/eth/source/transaction.service.ts, packages/eth/source/units.ts, packages/eth/source/wallet.dto.ts, pnpm-lock.yaml
web3 is almost [600kB in size](https://bundlephobia.com/package/web3@1.6.1) which is quite a lot for a browser. Replacing most web3 usage with specific methods from it which we used to not include more than we need. ~The `TransactionService` has one remaining call for `web3.eth.Contract` which should eventually also be replaced so that we can drop the web3 dependency.~
Replaced the `web3.eth.Contract` call with https://bundlephobia.com/package/web3-eth-contract@1.6.1 as a direct dependency. This saves roughly 1.2MB without gzip and 400kB with gzip.
=> refactor(eth): replace `web3` calls with more lightweight alternatives

packages/dot/package.json, packages/dot/source/ledger.service.ts, pnpm-lock.yaml
Switch to https://github.com/Zondax/ledger-substrate-js for DOT as the old package is no longer maintained.
=> chore(dot): replace `@zondax/ledger-polkadot` with `@zondax/ledger-substrate`

packages/ark/source/address.service.ts, packages/ark/source/crypto/identities/address.ts
[#752](https://github.com/PayvoHQ/wallet/issues/752)
Return network selection on address validation
-   [x] My changes look good in both light AND dark mode
-   [x] The change is not hardcoded to a single network, but has multi-asset in mind
-   [x] I checked my changes for obvious issues, debug statements and commented code
-   [x] Documentation _(if necessary)_
-   [x] Tests _(if necessary)_
-   [x] Ready to be merged
=> fix(ark): validate address based on network configuration

packages/ark/source/transaction.service.ts
Fixes Store an IPFS hash on the network that is failing because the constructor is receiving an incorrect parameter
which mean it also fixes one failing test from this issue https://github.com/PayvoHQ/wallet/issues/838
See failing test here https://github.com/PayvoHQ/wallet/blob/master/src/domains/transaction/cucumber/ipfs-transaction-multisig.ts
=> fix: multisignature signer initialization

packages/ark/source/networks/bind.mainnet.ts, packages/ark/source/networks/bind.testnet.ts
See https://github.com/PayvoHQ/wallet/issues/878.
=> chore(ark): disable vendorfields on BIND networks

packages/ark/source/fee.service.test.ts, packages/ark/source/fee.service.ts
Closes https://github.com/PayvoHQ/wallet/issues/859 (once released and updated on DW)
On the desktop wallet, [we use a stub transaction to calculate the multi-signature fees](https://github.com/PayvoHQ/wallet/blob/master/src/app/hooks/use-fees.ts#L84). The problem is that the SDK checks for the classname to return the proper values and since the transaction object is not a regular transaction it doesn't have a classname that makes the condition false and returns zero (which and the end causes the referred issue)
Plus, and is just an observation since wasn't able to find an easy way to test) I think that checking for the classname wouldn't work even if we used a regular transaction object since the constructor's names are usually updated to names like `a4` once compiled.
In summary, …
=> fix(ark): reliable way to calculate multisign fees

packages/profiles/source/environment.test.ts, packages/profiles/source/environment.ts
Adds a missing `await` to the profile persist method which is the cause of the bug described here https://github.com/PayvoHQ/wallet/issues/897 and others, for example, I noticed that sometimes when you update your name in the settings is not stored when you refresh
=> fix: profile not persisting randomly

packages/ark/source/ledger.service.test.ts, packages/ark/source/ledger.service.ts, packages/atom/source/ledger.service.test.ts, packages/btc/source/ledger.service.test.ts, packages/btc/source/ledger.service.ts, packages/dot/source/ledger.service.test.ts, packages/eos/source/ledger.service.test.ts, packages/eth/source/ledger.service.test.ts, packages/eth/source/ledger.service.ts, packages/lsk/source/ledger.service.test.ts, packages/lsk/source/ledger.service.ts, packages/neo/source/ledger.service.test.ts, packages/sdk/source/ledger.contract.ts, packages/sdk/source/ledger.service.ts, packages/trx/source/ledger.service.test.ts, packages/xlm/source/ledger.service.test.ts, packages/xrp/source/ledger.service.test.ts
Allows consumers to provide a utf8 string as message input instead of Buffer, when signing messages with ledger wallet.
Consumers won't be required to have Buffer dependency in order to sign a message.  See https://github.com/PayvoHQ/wallet/pull/957
=> refactor: accept payload as string in `LedgerService#signMessage`

packages/profiles/source/wallet-transaction.service.ts
Once updated on DW should fix https://github.com/ArkEcosystem/payvo-wallet/issues/990
Currently, when it tries to send a request in `packages/ark/source/multi-signature.service.ts@#post` it throws an exception with a `bignumber keyword validation` error for the nonce, the reason is that the payload is not created properly because the values for `nonce`, `amount` and `fee` are parsed as a regular plain objects which explains the validation error (those values are BigNumber instances before parsed with JSON.stringify/parse)
I am sending those values as strings since I think is  the safest way to send a big number without losing data but may require a second opinion from someone more familiarized with the SDK (I cant send theme as plain big number since it throws a JSON encoding exception)
=> fix(profiles): multisign transaction payload

packages/ark/source/ledger.service.ts
Related to https://github.com/ArkEcosystem/payvo-wallet/issues/1149 but can be closed until deps are updated in the desktop wallet.
Note that this issue happens because, in the step where we map the ledger wallets, not all the wallets are being passed to the `mapPathsToWallets` method because we don't have all yet in some cases (wallets are loaded in a loop). I let you know this because is not really easy to replicate the issue so maybe you can only focus on the code and ensure the new logic is correct and everything still works as expected (only if you have trouble in replicating the problem).
=> fix(ark): scan method giving incomplete data

packages/ark/source/link.service.test.ts, packages/ark/source/manifest.ts, packages/ark/source/networks/bind.testnet.ts, packages/ark/source/networks/shared.ts, packages/ark/source/networks/sxp.mainnet.ts, packages/ark/source/networks/sxp.testnet.ts
Adds configurations from https://github.com/Solar-network/desktop-wallet/blob/master/rebrand/node_modules/%40payvo/sdk-ark/distribution/cjs/networks/sxp.mainnet.js and https://github.com/Solar-network/desktop-wallet/blob/master/rebrand/node_modules/%40payvo/sdk-ark/distribution/cjs/networks/tsxp.testnet.js
=> chore(ark): add SXP networks

packages/ark/source/networks/sxp.mainnet.ts, packages/ark/source/networks/sxp.testnet.ts, packages/sdk/source/network-repository.test.ts
Adjusts the SXP network configs:
- remove `split` vote method to allow single transaction vote switches
- enable the IPFS transaction type
- increase multipayment limit to 256
=> chore(ark): adjust SXP network configs

packages/profiles/source/transaction.aggregate.test.ts, packages/profiles/source/transaction.aggregate.ts, packages/sdk/source/client.contract.ts
Adds an extra `networkId` field to the `WalletIdentifier` interface which can be used to also match against a wallets network in the transaction aggregate wallet lookup, in addition to the identifier value itself.
=> refactor(profiles): include network id in wallet lookup of transaction aggregate

packages/ark/source/signed-transaction.dto.ts, packages/sdk/source/signed-transaction.dto.ts
Normalizes transaction data by removing timestamp which is necessary for ark, and throws broadcast exceptions for ark-based coins like compendia.
=> fix(ark): normalize transaction data on broadcast

packages/profiles/source/host.repository.test.ts, packages/profiles/source/host.repository.ts
Since the check is against a falsy value if I Pass `0` to the forget method it removes all the items
=> fix: removing an element by index removes all items if using zero

packages/profiles/source/driver.ts
When getting the custom hosts we should only select the ones for the specific type that was passed, otherwise, it creates a scenario where customHosts.length>1 but there are no really any custom host to get in the random function
=> fix(profiles): ensure custom hosts are for the selected type
